### ISSUE TITLE
Warn user if he wants to leave the editor without saving

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [MyrionPhoenixmoon/scenarioo#136]
If it is not possible, then maybe alert the user on reloading that information was lost. -> We agreed to implement this.

**Comment by adiherzog** [comment]
An option would be to store it into local storage. We already use an angular local storage module for certain cases.

But I think this is quite low prio. The user should not do a full page reload (which is equal to reloading the entire Angular app).

**Comment by adiherzog** [comment]
@MyrionPhoenixmoon Please have a look at the TODO I added. ESLint was not happy with your checking.

**Comment by MyrionPhoenixmoon** [comment]
About the TODOs and the commented-out part:

I think that ESLint is right in general to warn about the confirm dialogs, but that we've got a legitimate usecase here. // eslint-disable-line is therefore my Proposal on the confirm dialog.

As for the webtests breaking due to "onbeforeunload", I think we will have to fix the webtests to deal with that, since as far as I can tell, there is no other way to handle a reload. Alternatively, we deal with reloads by trying to save all information we can in cookies.

**Comment by adiherzog** [comment]
I agree with your comments. Please always run the web tests before you check in a change in the future to make sure it does not break.

**Comment by adiherzog** [comment]
We could probably use an existing Angular directive for this (e.g. https://github.com/facultymatt/angular-unsavedChanges).

@MyrionPhoenixmoon Do you want to give this a try?

**Comment by adiherzog** [comment]
Using angular-unsavedChanges now to detect unsaved changes.
