### ISSUE TITLE
Icon design

### ISSUE THREAD

**Issue by parabolika66** [MyrionPhoenixmoon/scenarioo#142]
- Button Tool: background color should be gray (maybe with 3d effect) or use rounded corners. "abc" is confusing. Red as color is not an option.
- Text tool: T as an icon

**Comment by MyrionPhoenixmoon** [comment]
For the z-axis manipulation buttons, a hotfix could be to change the text to "Bring to front" and "send to back" as well as Move one layer back / forward".
