### ISSUE TITLE
Style related sketches list like all other metadata lists

### ISSUE THREAD

**Issue by adiherzog** [MyrionPhoenixmoon/scenarioo#191]

**Comment by adiherzog** [comment]
There's too much whitespace when I look at it in Chrome. @MyrionPhoenixmoon Is this just my browser or does it look the same for you?

![whitespace](https://cloud.githubusercontent.com/assets/3780183/11428441/bb79edaa-946b-11e5-8786-df78d1acf6e6.png)

**Comment by MyrionPhoenixmoon** [comment]
Yes, I can see it too. I'd fixed the error in the CSS file, but not the LESS file, and pushing it all didn't include the CSS file.
I'm sorry I didn't spot that.

**Comment by adiherzog** [comment]
Yeah, the CSS file is always generated from the LESS file by the gulp task and therefore must not be checked in and must not be changed. So please just put your changes into `scenarioo.less`. Thanks :-)

**Comment by adiherzog** [comment]
Looks good now, thanks :+1:
