### ISSUE TITLE
Add step number in the metadata tab for the link to the related step

### ISSUE THREAD

**Issue by adiherzog** [MyrionPhoenixmoon/scenarioo#192]

**Comment by MyrionPhoenixmoon** [comment]
I have the code prepared, but I noticed that the steps are internally 0-indexed, but presented to the user 1-indexed. I would therefore also present a 1-indexed step number.

Or is there a reason not to do so?

**Comment by adiherzog** [comment]
You are right. The index in the UI should be 1-indexed.
