### ISSUE TITLE
Highlight Areas of a Sketch

### ISSUE THREAD

**Issue by parabolika66** [MyrionPhoenixmoon/scenarioo#21]
As a user I want to mark areas on a screenshot in order to highlight a certain aspect.

Style: Yellow marker, like in Windows Snipping tool

Implement it as a rectangle with yellow background and low opacity.

**Comment by parabolika66** [comment]
Steps to create a new CompositeDrawTool:
- extend svg.compsiteShape.js
- extend the function createNewShapeByClassName in drawShape.service.js
- create a new tool service (e.g. highlightCompositeDrawTool.js)
- add this new file to index.html
- add the new service to the toolbox service (toolBox.service.js)

**Comment by adiherzog** [comment]
Looks good :+1: Therefore I close this.
