### ISSUE TITLE
Create basic View/Controller for Issues List (Custom Tab on Main View)

### ISSUE THREAD

**Issue by parabolika66** [MyrionPhoenixmoon/scenarioo#55]
Custom viewm/controller with dummy data that links to a single issue, see #51 

Parent User Story: #8

**Comment by bruderol** [comment]
Hi @parabolika66 and @MyrionPhoenixmoon 
Cool to see, that you make progress on this project :smiley: :+1: 
Just a short recommendation: it is best practice to provide the issue number on each commit comment like this "#55 bla bla" ... This will help to see on each issue which commits solved a story, which is very helpful for reviews.
Happy coding :smiley:

**Comment by parabolika66** [comment]
Hi @bruderol
Good point! Will do ;)
Cheers
