### ISSUE TITLE
Store basic ScenarioSketch on Server

### ISSUE THREAD

**Issue by parabolika66** [MyrionPhoenixmoon/scenarioo#72]
Store ScenarioSketch in respective directory.

**Comment by parabolika66** [comment]
New: "ScenarioSketch"

**Comment by parabolika66** [comment]
Estimate: 2h

**Comment by MyrionPhoenixmoon** [comment]
This requires the Issue creation to return the Issue ID to the front-end for the Usecase where an Issue is created at the same time as a Sketch and ScenarioSketch.
The ScenarioSketch should be added to the Issue by ID, and therefore the front end needs to have the ID available.
